"""all cols created

Revision ID: 4ee53f7b80a4
Revises: 790032e435d0
Create Date: 2018-08-29 20:08:07.230271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee53f7b80a4'
down_revision = '790032e435d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('gain', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('market_price', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('stocks', sa.Column('target_price', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('txn_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'txn_price')
    op.drop_column('stocks', 'target_price')
    op.drop_column('stocks', 'quantity')
    op.drop_column('stocks', 'market_price')
    op.drop_column('stocks', 'gain')
    # ### end Alembic commands ###
